<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class LabTestCatalogSeeder extends Seeder
{
    public function run()
    {
        // Check if table exists first
        if (!$this->db->tableExists('lab_test_catalog')) {
            log_message('warning', 'lab_test_catalog table does not exist. Please run the migration first.');
            return;
        }

        $data = [
            // Blood Tests
            [
                'test_name' => 'Complete Blood Count (CBC)',
                'test_type' => 'Hematology',
                'specimen_category' => 'with_specimen',
                'description' => 'Complete blood count including red blood cells, white blood cells, and platelets',
                'normal_range' => 'RBC: 4.5-5.5 million/μL, WBC: 4,000-11,000/μL, Platelets: 150,000-450,000/μL',
                'price' => 300.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Blood Glucose (Fasting)',
                'test_type' => 'Chemistry',
                'specimen_category' => 'with_specimen',
                'description' => 'Fasting blood sugar level test',
                'normal_range' => '70-100 mg/dL',
                'price' => 150.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Lipid Profile',
                'test_type' => 'Chemistry',
                'specimen_category' => 'with_specimen',
                'description' => 'Complete lipid panel including cholesterol and triglycerides',
                'normal_range' => 'Total Cholesterol: <200 mg/dL, LDL: <100 mg/dL, HDL: >40 mg/dL',
                'price' => 400.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Hemoglobin A1C',
                'test_type' => 'Chemistry',
                'specimen_category' => 'with_specimen',
                'description' => 'Glycated hemoglobin test for diabetes monitoring',
                'normal_range' => '<5.7%',
                'price' => 350.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Liver Function Test (LFT)',
                'test_type' => 'Chemistry',
                'specimen_category' => 'with_specimen',
                'description' => 'Comprehensive liver function panel',
                'normal_range' => 'ALT: 7-56 U/L, AST: 10-40 U/L, Bilirubin: 0.1-1.2 mg/dL',
                'price' => 450.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Kidney Function Test (KFT)',
                'test_type' => 'Chemistry',
                'specimen_category' => 'with_specimen',
                'description' => 'Renal function panel including creatinine and BUN',
                'normal_range' => 'Creatinine: 0.6-1.2 mg/dL, BUN: 7-20 mg/dL',
                'price' => 400.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // Urine Tests
            [
                'test_name' => 'Urinalysis',
                'test_type' => 'Urine Analysis',
                'specimen_category' => 'with_specimen',
                'description' => 'Complete urine analysis including physical, chemical, and microscopic examination',
                'normal_range' => 'pH: 4.6-8.0, Specific Gravity: 1.005-1.030',
                'price' => 200.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Urine Culture',
                'test_type' => 'Microbiology',
                'specimen_category' => 'with_specimen',
                'description' => 'Bacterial culture and sensitivity test for urinary tract infections',
                'normal_range' => 'No growth',
                'price' => 500.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // Imaging Tests
            [
                'test_name' => 'Chest X-Ray',
                'test_type' => 'Radiology',
                'specimen_category' => 'without_specimen',
                'description' => 'Chest radiograph for lung and heart evaluation',
                'normal_range' => 'Normal lung fields, normal heart size',
                'price' => 800.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Abdominal Ultrasound',
                'test_type' => 'Radiology',
                'specimen_category' => 'without_specimen',
                'description' => 'Ultrasound examination of abdominal organs',
                'normal_range' => 'Normal organ size and appearance',
                'price' => 1200.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'ECG (Electrocardiogram)',
                'test_type' => 'Cardiology',
                'specimen_category' => 'without_specimen',
                'description' => 'Electrocardiogram for heart rhythm and function',
                'normal_range' => 'Normal sinus rhythm',
                'price' => 600.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // Pathology Tests
            [
                'test_name' => 'Pap Smear',
                'test_type' => 'Pathology',
                'specimen_category' => 'with_specimen',
                'description' => 'Cervical cytology screening test',
                'normal_range' => 'Negative for intraepithelial lesion',
                'price' => 700.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // Other Tests
            [
                'test_name' => 'Thyroid Function Test (TFT)',
                'test_type' => 'Endocrinology',
                'specimen_category' => 'with_specimen',
                'description' => 'Thyroid hormone levels including TSH, T3, T4',
                'normal_range' => 'TSH: 0.4-4.0 mIU/L, T4: 4.5-11.2 μg/dL',
                'price' => 500.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Vitamin D Level',
                'test_type' => 'Chemistry',
                'specimen_category' => 'with_specimen',
                'description' => '25-Hydroxyvitamin D level test',
                'normal_range' => '30-100 ng/mL',
                'price' => 600.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // Additional Blood Tests
            [
                'test_name' => 'Blood Type & Rh Factor',
                'test_type' => 'Hematology',
                'specimen_category' => 'with_specimen',
                'description' => 'Blood group typing and Rh factor determination',
                'normal_range' => 'A, B, AB, or O with Rh+ or Rh-',
                'price' => 250.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'ESR (Erythrocyte Sedimentation Rate)',
                'test_type' => 'Hematology',
                'specimen_category' => 'with_specimen',
                'description' => 'Erythrocyte sedimentation rate test',
                'normal_range' => 'Men: 0-15 mm/hr, Women: 0-20 mm/hr',
                'price' => 200.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Coagulation Profile (PT/PTT)',
                'test_type' => 'Hematology',
                'specimen_category' => 'with_specimen',
                'description' => 'Prothrombin time and partial thromboplastin time',
                'normal_range' => 'PT: 11-13.5 sec, PTT: 25-35 sec',
                'price' => 450.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Blood Urea Nitrogen (BUN)',
                'test_type' => 'Chemistry',
                'specimen_category' => 'with_specimen',
                'description' => 'Blood urea nitrogen test for kidney function',
                'normal_range' => '7-20 mg/dL',
                'price' => 180.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Serum Creatinine',
                'test_type' => 'Chemistry',
                'specimen_category' => 'with_specimen',
                'description' => 'Creatinine level test for kidney function',
                'normal_range' => 'Men: 0.7-1.3 mg/dL, Women: 0.6-1.1 mg/dL',
                'price' => 150.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Serum Electrolytes',
                'test_type' => 'Chemistry',
                'specimen_category' => 'with_specimen',
                'description' => 'Sodium, potassium, chloride, and bicarbonate levels',
                'normal_range' => 'Na: 136-145 mEq/L, K: 3.5-5.0 mEq/L, Cl: 98-107 mEq/L',
                'price' => 350.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'HbA1c (Glycated Hemoglobin)',
                'test_type' => 'Chemistry',
                'specimen_category' => 'with_specimen',
                'description' => 'Average blood sugar level over 2-3 months',
                'normal_range' => '<5.7% (Normal), 5.7-6.4% (Prediabetes), ≥6.5% (Diabetes)',
                'price' => 400.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'C-Reactive Protein (CRP)',
                'test_type' => 'Chemistry',
                'specimen_category' => 'with_specimen',
                'description' => 'Inflammation marker test',
                'normal_range' => '<3.0 mg/L',
                'price' => 300.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Troponin I',
                'test_type' => 'Chemistry',
                'specimen_category' => 'with_specimen',
                'description' => 'Cardiac marker for heart attack detection',
                'normal_range' => '<0.04 ng/mL',
                'price' => 500.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // Urine Tests
            [
                'test_name' => 'Urine Pregnancy Test',
                'test_type' => 'Urine Analysis',
                'specimen_category' => 'with_specimen',
                'description' => 'Pregnancy detection test',
                'normal_range' => 'Positive or Negative',
                'price' => 150.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => '24-Hour Urine Collection',
                'test_type' => 'Urine Analysis',
                'specimen_category' => 'with_specimen',
                'description' => 'Complete 24-hour urine collection for comprehensive analysis',
                'normal_range' => 'Varies by test',
                'price' => 400.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // Imaging Tests
            [
                'test_name' => 'X-Ray (Any Body Part)',
                'test_type' => 'Radiology',
                'specimen_category' => 'without_specimen',
                'description' => 'X-ray imaging for bone and tissue evaluation',
                'normal_range' => 'Normal bone structure, no fractures',
                'price' => 600.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'CT Scan (Computed Tomography)',
                'test_type' => 'Radiology',
                'specimen_category' => 'without_specimen',
                'description' => 'Detailed cross-sectional imaging',
                'normal_range' => 'Normal organ appearance',
                'price' => 3500.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'MRI (Magnetic Resonance Imaging)',
                'test_type' => 'Radiology',
                'specimen_category' => 'without_specimen',
                'description' => 'Magnetic resonance imaging for soft tissue evaluation',
                'normal_range' => 'Normal tissue appearance',
                'price' => 5000.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Echocardiogram',
                'test_type' => 'Cardiology',
                'specimen_category' => 'without_specimen',
                'description' => 'Ultrasound of the heart',
                'normal_range' => 'Normal heart structure and function',
                'price' => 2000.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Mammography',
                'test_type' => 'Radiology',
                'specimen_category' => 'without_specimen',
                'description' => 'Breast X-ray for cancer screening',
                'normal_range' => 'No abnormalities detected',
                'price' => 1500.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // Microbiology Tests
            [
                'test_name' => 'Blood Culture',
                'test_type' => 'Microbiology',
                'specimen_category' => 'with_specimen',
                'description' => 'Bacterial culture from blood sample',
                'normal_range' => 'No growth',
                'price' => 800.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Sputum Culture',
                'test_type' => 'Microbiology',
                'specimen_category' => 'with_specimen',
                'description' => 'Bacterial culture from sputum sample',
                'normal_range' => 'Normal flora or no growth',
                'price' => 600.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Stool Culture',
                'test_type' => 'Microbiology',
                'specimen_category' => 'with_specimen',
                'description' => 'Bacterial culture from stool sample',
                'normal_range' => 'Normal flora',
                'price' => 500.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Throat Swab Culture',
                'test_type' => 'Microbiology',
                'specimen_category' => 'with_specimen',
                'description' => 'Bacterial culture from throat swab',
                'normal_range' => 'Normal flora or no growth',
                'price' => 400.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // Pathology Tests
            [
                'test_name' => 'Biopsy (Any Site)',
                'test_type' => 'Pathology',
                'specimen_category' => 'with_specimen',
                'description' => 'Tissue sample examination',
                'normal_range' => 'Benign, no malignancy',
                'price' => 1500.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Fine Needle Aspiration (FNA)',
                'test_type' => 'Pathology',
                'specimen_category' => 'with_specimen',
                'description' => 'Cytology from fine needle aspiration',
                'normal_range' => 'Benign cells',
                'price' => 1200.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // Endocrinology Tests
            [
                'test_name' => 'TSH (Thyroid Stimulating Hormone)',
                'test_type' => 'Endocrinology',
                'specimen_category' => 'with_specimen',
                'description' => 'Thyroid function screening test',
                'normal_range' => '0.4-4.0 mIU/L',
                'price' => 300.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Free T4 (Thyroxine)',
                'test_type' => 'Endocrinology',
                'specimen_category' => 'with_specimen',
                'description' => 'Free thyroxine level',
                'normal_range' => '0.8-1.8 ng/dL',
                'price' => 350.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Cortisol Level',
                'test_type' => 'Endocrinology',
                'specimen_category' => 'with_specimen',
                'description' => 'Adrenal hormone level test',
                'normal_range' => 'Morning: 10-20 μg/dL, Evening: 3-10 μg/dL',
                'price' => 400.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
            // Other Common Tests
            [
                'test_name' => 'PSA (Prostate Specific Antigen)',
                'test_type' => 'Oncology',
                'specimen_category' => 'with_specimen',
                'description' => 'Prostate cancer screening test',
                'normal_range' => '<4.0 ng/mL',
                'price' => 500.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'CA 125 (Cancer Antigen)',
                'test_type' => 'Oncology',
                'specimen_category' => 'with_specimen',
                'description' => 'Ovarian cancer marker',
                'normal_range' => '<35 U/mL',
                'price' => 600.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Ferritin Level',
                'test_type' => 'Hematology',
                'specimen_category' => 'with_specimen',
                'description' => 'Iron storage protein level',
                'normal_range' => 'Men: 20-500 ng/mL, Women: 20-200 ng/mL',
                'price' => 350.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Vitamin B12 Level',
                'test_type' => 'Chemistry',
                'specimen_category' => 'with_specimen',
                'description' => 'Vitamin B12 deficiency test',
                'normal_range' => '200-900 pg/mL',
                'price' => 400.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'test_name' => 'Folate Level',
                'test_type' => 'Chemistry',
                'specimen_category' => 'with_specimen',
                'description' => 'Folic acid level test',
                'normal_range' => '>4.0 ng/mL',
                'price' => 350.00,
                'is_active' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $builder = $this->db->table('lab_test_catalog');
        foreach ($data as $row) {
            // Check by test_name to avoid duplicates
            $exists = $builder->where('test_name', $row['test_name'])->get()->getFirstRow('array');
            if ($exists) {
                // Update if already present
                $builder->where('id', $exists['id'])->update([
                    'test_type' => $row['test_type'],
                    'specimen_category' => $row['specimen_category'],
                    'description' => $row['description'],
                    'normal_range' => $row['normal_range'],
                    'price' => $row['price'],
                    'is_active' => $row['is_active'],
                    'updated_at' => date('Y-m-d H:i:s'),
                ]);
            } else {
                $builder->insert($row);
            }
        }
    }
}

